name: Update Canucks Banner

on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  capture-banner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get banner image
        run: |
          curl -o banner.png "https://shot.screenshotapi.net/screenshot?token=${{ secrets.SCREENSHOT_API_KEY }}&url=https://www.nhl.com/canucks/&width=1920&height=1080&crop_area=%7B%22x%22:0,%22y%22:0,%22width%22:1920,%22height%22:350%7D&output=image"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add banner.png
          git commit -m "Update banner" || echo "No changes to commit"
          git push
